In [3]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 20 ms


In [5]:
%time for _ in range(10): my_list2 = my_list * 2

Wall time: 152 ms


In [6]:
data = np.random.randn(2,3)

In [7]:
data

array([[-1.54078807, -0.58329257, -0.35027627],
       [ 2.5651516 , -0.46503048,  1.084692  ]])

In [8]:
data * 10

array([[-15.40788068,  -5.83292573,  -3.50276268],
       [ 25.65151601,  -4.65030478,  10.84691996]])

In [9]:
data + data

array([[-3.08157614, -1.16658515, -0.70055254],
       [ 5.1303032 , -0.93006096,  2.16938399]])

In [10]:
# shape 表示各维度大小
data.shape

(2, 3)

In [11]:
# dtype 表示数组数据类型
data.dtype

dtype('float64')

In [30]:
# 创建ndarray对象
data1 = [6,7,8]
arr1 = np.array(data1)

In [31]:
arr1

array([6, 7, 8])

In [23]:
data2 = [[1.23,1.1,2.33],[2.1,2.4,1.22]]
arr2 = np.array(data2)

In [24]:
arr2

array([[1.23, 1.1 , 2.33],
       [2.1 , 2.4 , 1.22]])

In [25]:
arr2.shape

(2, 3)

In [26]:
arr2.ndim

2

In [32]:
arr1.shape

(3,)

In [33]:
arr1.dtype

dtype('int32')

In [34]:
arr2.dtype

dtype('float64')

In [35]:
# 创建全是0数组
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
# 创建全是1的数组
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
# arange 是 python内置函数range的数组版
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])